More buttons for queue managment
LessonsQueue/QueueManagerFront pull request #13
Opened 2024-05-30 19:39 UTC by KobbAsa

2024-05-30 19:42 UTC, SharpDevOps10 requested changes

2024-05-30 19:42 UTC, SharpDevOps10 commented on src/components/Queue.svelte
> +    }
It is better to use single quotes

2024-05-30 19:54 UTC, thebladehit approved these changes

2024-05-31 06:03 UTC, SharpDevOps10 approved these changes

2024-05-31 06:03 UTC, merged