Added authorization components
LessonsQueue/QueueManagerFront pull request #5
Opened 2024-05-20 16:05 UTC by KobbAsa

2024-05-20 18:20 UTC, radichenko requested changes

2024-05-20 18:20 UTC, radichenko commented on src/components/Auth/Auth.svelte
> +    }
It is better to use arrow functions

2024-05-20 18:20 UTC, radichenko commented on src/components/Auth/LoginForm.svelte
> +    }
It is better to use arrow functions

2024-05-20 18:20 UTC, radichenko commented on src/components/Auth/SignUpForm.svelte
> +    }
It is better to use arrow functions

2024-05-20 18:32 UTC, thebladehit requested changes

2024-05-20 18:32 UTC, thebladehit commented on src/components/Auth/Auth.svelte
> +    function handleLogin(event) {
use arrow functions

2024-05-20 20:38 UTC, SharpDevOps10 requested changes

2024-05-20 20:38 UTC, SharpDevOps10 commented on src/components/Auth/Auth.svelte
> +    }
use arrow functions

2024-05-21 07:06 UTC, SharpDevOps10 approved these changes

2024-05-21 13:30 UTC, thebladehit approved these changes

2024-05-21 13:30 UTC, merged