Implement register and login
LessonsQueue/QueueManagerFront pull request #7
Opened 2024-05-21 19:51 UTC by thebladehit

2024-05-21 20:17 UTC, SharpDevOps10 requested changes

2024-05-21 20:17 UTC, SharpDevOps10 commented on src/components/Auth/Auth.svelte
> +        // showMessage('success', 'you are logined')
Remove these comments from code

2024-05-21 20:17 UTC, SharpDevOps10 commented on src/components/Auth/Auth.svelte
> +        // showMessage('success', 'you are registerd')
Remove these comments from code

2024-05-22 17:32 UTC, thebladehit commented on src/components/Auth/Auth.svelte
> +        // showMessage('success', 'you are registerd')
In future

2024-05-22 19:10 UTC, KobbAsa approved these changes

2024-05-22 19:14 UTC, SharpDevOps10 approved these changes

2024-05-22 19:14 UTC, merged